dropzoneapp/urls.py
from django.urls import path
from . import views
from dropzoneapp.views import MainView

app_name = 'dropzoneapp'

urlpatterns = [
    path('', MainView.as_view(), name="index"),
    path('upload/', views.file_upload_view, name='file_upload'),
    path('file_list/', views.file_list_view, name='file_list'),
    path('delete_file/<int:file_id>/', views.delete_file, name='delete_file'),
    path('download_file/<int:file_id>/', views.download_file, name='download_file'),
    #path('file_download/<int:file_id>/', views.FileDownloadView.as_view(), name='file_download'),

]

dropzoneproje/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("dropzoneapp.urls")),
    path('admin/', admin.site.urls),
]

dropzoneapp/models.py
from django.db import models

# Create your models here.
class Dropzonemodel(models.Model):
    upload = models.FileField(upload_to='media/')

    def __str__(self):
        return str(self.pk)
    


class UploadedFile(models.Model):
    file = models.FileField(upload_to='')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

dropzoneapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView   
from django.http import HttpResponse, JsonResponse,  Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from django.http import FileResponse
from django.core.files.storage import default_storage
from django.views import View


"""def index(request):
    return HttpResponse("deneme")"""

class MainView(TemplateView):
    template_name = 'dropzoneapp/index.html'

def file_upload_view(request):
    print(request.FILES)
    return HttpResponse('upload')

from .models import UploadedFile

def file_upload_view(request):
    if request.method == 'POST':
        uploaded_file = request.FILES.get('file')
        if uploaded_file:
            # Dosyayı işle ve veritabanına kaydet
            new_file = UploadedFile(file=uploaded_file)
            new_file.save()

            # Başarılı yanıt
            return JsonResponse({'message': 'Dosya başarıyla yüklendi.'}, status=200)
        else:
            # Dosya yüklenmediğinde hata yanıtı
            return JsonResponse({'error': 'Dosya yüklenirken bir hata oluştu.'}, status=400)
    else:
        # POST isteği dışında gelen isteklere hata yanıtı
        return JsonResponse({'error': 'Geçersiz istek yöntemi.'}, status=405)


def file_list_view(request):
    files = UploadedFile.objects.all()  # models.py'deki modele göre
    return render(request, 'dropzoneapp/file_list.html', {'files': files})

def delete_file(request, file_id):
    file_to_delete = get_object_or_404(models.UploadedFile, id=file_id)
    file_to_delete.delete()
    return redirect('dropzoneapp:file_list')


    
import mimetypes

def download_file(request, file_id):
    file_instance = get_object_or_404(UploadedFile, id=file_id)
    file_path = file_instance.file.path

    # MIME türünü belirle
    mime_type, encoding = mimetypes.guess_type(file_path)

    # Dosyayı aç ve kullanıcıya gönder
    try:
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type=mime_type)
            response['Content-Disposition'] = f'attachment; filename="{file_instance.file.name}"'
            return response
    except FileNotFoundError:
        raise Http404("Belirtilen dosya bulunamadı.")

dropzoneapp/templates/dropzoneapp/file_list.html
{% extends "base.html" %}

{% block content %}
  <h3>Yüklenen Dosyalar</h3>
  =<ul>
    {% for file in files %}
      <li><a href="{{ file.file.url }}" target="_blank">{{ file.file.name }}</a></li>
      <a href="{% url 'dropzoneapp:delete_file' file.id %}">Sil</a>
      
      <a href="{% url 'dropzoneapp:download_file' file_id=file.id %}">Dosyayı İndir</a>
    {% endfor %}
  </ul>

          


{% endblock %}

dropzoneapp/templates/dropzoneapp/index.html
{% extends "base.html" %}

{%block content%}
<h3>jasdfjadsjfh</h3>


<!-- burdaki slaslar cok onemli          /upload/        -->
<form action="/upload/" method="POST" class="dropzone" id="my-awesome-dropzone">
    {% csrf_token %}
    <div class="fallback">
        <input name="file" type="file" multiple>
    </div>
</form>

{%endblock%}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
    <title>Document</title>
</head>
<body>
    
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'dropzoneapp:index' %}">DROPZONE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dropzoneapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dropzoneapp:file_list' %}">yuklenenler</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>

    {% block content %}

    {% endblock %}
</body>
</html>